### ISSUE TITLE
Unable to run the Showcase app

### ISSUE THREAD

**Issue by ekahannah** [skiptools/skipapp-showcase#1]
Hi, 

I encountered this issue when running the 0.2.12 version of the app: 
![Screenshot 2023-11-21 at 10 45 15 AM](https://github.com/skiptools/skipapp-showcase/assets/1568192/ffa47c24-1197-488f-ad9e-00745f1f54c3)

I think this started from this Modernize project layout commit: 818cbb0c9f33971dcfd5e275a292a251fcd647ef

I had the similar problem here:
https://github.com/skiptools/skipapp-databake/issues/1

Do you have any ideas to resolve the issue? Thanks!

**Comment by marcprux** [comment]
Did you have a previous version of the app checked out before that commit? Because the project structure changed: the new project is located in the `Darwin/` folder, and your error message shows the top-level `Showcase.xcodeproj` file (which should no longer be available).

Can you try checking out a fresh version of the project and opening the project in the `Darwin` folder and let us know if the issue persists?

**Comment by ekahannah** [comment]
Hi @marcprux ,

Yes, I did have a previous version of the app checked out. 
Checking out the fresh version of the project did the trick.

Thanks!
